// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '4004a9fd-d58e-48dc-aeb2-4a4aec58606f',
    name: 'Free Trial',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '1273adef-00a3-4086-a51a-dbcce1857d36',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_AD_TEST_USER_PRINCIPAL_NAME'] = 'testUserAuto@rbacCliTest.onmicrosoft.com';
  process.env['AZURE_AD_TEST_PASSWORD'] = 'Pa$$w0rd';
  process.env['AZURE_AD_TEST_GROUP_NAME'] = 'testgroupauto';
  process.env['AZURE_ARM_TEST_LOCATION'] = 'West US';
  process.env['AZURE_AD_TEST_SP_DISPLAY_NAME'] = 'mytestapprandomauto0012345';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29?api-version=2015-07-01', '*')
  .reply(201, "{\"properties\":{\"roleName\":\"TestRole_24a227ee-48d8-4225-be90-49c22fd203e7\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:40.8672516Z\",\"updatedOn\":\"2015-11-17T18:04:40.8672516Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"11f74e93-895c-47b2-908f-a9794316ef29\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '5e9d7ce9-7411-4f18-85f7-f158a64aee14',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_0',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': '4235dc28-60a2-4d3e-9273-9b2be1d26d70',
  'x-ms-routing-request-id': 'WESTUS:20151117T180441Z:4235dc28-60a2-4d3e-9273-9b2be1d26d70',
  date: 'Tue, 17 Nov 2015 18:04:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29?api-version=2015-07-01', '*')
  .reply(201, "{\"properties\":{\"roleName\":\"TestRole_24a227ee-48d8-4225-be90-49c22fd203e7\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:40.8672516Z\",\"updatedOn\":\"2015-11-17T18:04:40.8672516Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"11f74e93-895c-47b2-908f-a9794316ef29\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '5e9d7ce9-7411-4f18-85f7-f158a64aee14',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_0',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': '4235dc28-60a2-4d3e-9273-9b2be1d26d70',
  'x-ms-routing-request-id': 'WESTUS:20151117T180441Z:4235dc28-60a2-4d3e-9273-9b2be1d26d70',
  date: 'Tue, 17 Nov 2015 18:04:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29?api-version=2015-07-01')
  .reply(200, "{\"properties\":{\"roleName\":\"TestRole_24a227ee-48d8-4225-be90-49c22fd203e7\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:40.8672516Z\",\"updatedOn\":\"2015-11-17T18:04:40.8672516Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"11f74e93-895c-47b2-908f-a9794316ef29\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '2f91a017-3268-4163-9d09-18cfa06d5f14',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': 'ed7e1c78-547f-4a0e-a7b2-60207a7ebe33',
  'x-ms-routing-request-id': 'WESTUS:20151117T180442Z:ed7e1c78-547f-4a0e-a7b2-60207a7ebe33',
  date: 'Tue, 17 Nov 2015 18:04:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29?api-version=2015-07-01')
  .reply(200, "{\"properties\":{\"roleName\":\"TestRole_24a227ee-48d8-4225-be90-49c22fd203e7\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:40.8672516Z\",\"updatedOn\":\"2015-11-17T18:04:40.8672516Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"11f74e93-895c-47b2-908f-a9794316ef29\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '2f91a017-3268-4163-9d09-18cfa06d5f14',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': 'ed7e1c78-547f-4a0e-a7b2-60207a7ebe33',
  'x-ms-routing-request-id': 'WESTUS:20151117T180442Z:ed7e1c78-547f-4a0e-a7b2-60207a7ebe33',
  date: 'Tue, 17 Nov 2015 18:04:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29?api-version=2015-07-01', '*')
  .reply(201, "{\"properties\":{\"roleName\":\"UpdatedRole_77227b4e-5e1f-4ce5-bfd0-ad0b483a7ca7\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:42.4181887Z\",\"updatedOn\":\"2015-11-17T18:04:42.4181887Z\",\"createdBy\":null,\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"11f74e93-895c-47b2-908f-a9794316ef29\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '723',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '25dcdb73-6986-4131-b466-f53bdc7b4606',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_1',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-correlation-request-id': 'b278951a-182f-44db-b882-363c9d7f1e1d',
  'x-ms-routing-request-id': 'WESTUS:20151117T180443Z:b278951a-182f-44db-b882-363c9d7f1e1d',
  date: 'Tue, 17 Nov 2015 18:04:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29?api-version=2015-07-01', '*')
  .reply(201, "{\"properties\":{\"roleName\":\"UpdatedRole_77227b4e-5e1f-4ce5-bfd0-ad0b483a7ca7\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:42.4181887Z\",\"updatedOn\":\"2015-11-17T18:04:42.4181887Z\",\"createdBy\":null,\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"11f74e93-895c-47b2-908f-a9794316ef29\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '723',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '25dcdb73-6986-4131-b466-f53bdc7b4606',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_1',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1196',
  'x-ms-correlation-request-id': 'b278951a-182f-44db-b882-363c9d7f1e1d',
  'x-ms-routing-request-id': 'WESTUS:20151117T180443Z:b278951a-182f-44db-b882-363c9d7f1e1d',
  date: 'Tue, 17 Nov 2015 18:04:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29?api-version=2015-07-01')
  .reply(200, "{\"properties\":{\"roleName\":\"UpdatedRole_77227b4e-5e1f-4ce5-bfd0-ad0b483a7ca7\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:40.8672516Z\",\"updatedOn\":\"2015-11-17T18:04:42.4181887Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"11f74e93-895c-47b2-908f-a9794316ef29\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '757',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '544e6771-9faa-485f-bfd3-1005652ba591',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': 'c071b3f6-08e1-4179-a7e6-0c36498533fb',
  'x-ms-routing-request-id': 'WESTUS:20151117T180443Z:c071b3f6-08e1-4179-a7e6-0c36498533fb',
  date: 'Tue, 17 Nov 2015 18:04:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29?api-version=2015-07-01')
  .reply(200, "{\"properties\":{\"roleName\":\"UpdatedRole_77227b4e-5e1f-4ce5-bfd0-ad0b483a7ca7\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:40.8672516Z\",\"updatedOn\":\"2015-11-17T18:04:42.4181887Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"11f74e93-895c-47b2-908f-a9794316ef29\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '757',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '544e6771-9faa-485f-bfd3-1005652ba591',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': 'c071b3f6-08e1-4179-a7e6-0c36498533fb',
  'x-ms-routing-request-id': 'WESTUS:20151117T180443Z:c071b3f6-08e1-4179-a7e6-0c36498533fb',
  date: 'Tue, 17 Nov 2015 18:04:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29?api-version=2015-07-01')
  .reply(200, "{\"properties\":{\"roleName\":\"UpdatedRole_77227b4e-5e1f-4ce5-bfd0-ad0b483a7ca7\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:40.8672516Z\",\"updatedOn\":\"2015-11-17T18:04:42.4181887Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"11f74e93-895c-47b2-908f-a9794316ef29\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '757',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '8f4db44a-7512-4694-9cfc-0783cccb22fa',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_1',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': 'e615b130-dbe1-4a8b-887c-d3f69530c8fd',
  'x-ms-routing-request-id': 'WESTUS:20151117T180444Z:e615b130-dbe1-4a8b-887c-d3f69530c8fd',
  date: 'Tue, 17 Nov 2015 18:04:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29?api-version=2015-07-01')
  .reply(200, "{\"properties\":{\"roleName\":\"UpdatedRole_77227b4e-5e1f-4ce5-bfd0-ad0b483a7ca7\",\"type\":\"CustomRole\",\"description\":\"Updated Role Description\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:40.8672516Z\",\"updatedOn\":\"2015-11-17T18:04:42.4181887Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/11f74e93-895c-47b2-908f-a9794316ef29\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"11f74e93-895c-47b2-908f-a9794316ef29\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '757',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '8f4db44a-7512-4694-9cfc-0783cccb22fa',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_1',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': 'e615b130-dbe1-4a8b-887c-d3f69530c8fd',
  'x-ms-routing-request-id': 'WESTUS:20151117T180444Z:e615b130-dbe1-4a8b-887c-d3f69530c8fd',
  date: 'Tue, 17 Nov 2015 18:04:44 GMT',
  connection: 'close' });
 return result; }]];
 exports.uuidsGenerated = function() { return ['24a227ee-48d8-4225-be90-49c22fd203e7','11f74e93-895c-47b2-908f-a9794316ef29','77227b4e-5e1f-4ce5-bfd0-ad0b483a7ca7'];};