// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '4004a9fd-d58e-48dc-aeb2-4a4aec58606f',
    name: 'Free Trial',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '1273adef-00a3-4086-a51a-dbcce1857d36',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_AD_TEST_USER_PRINCIPAL_NAME'] = 'testUserAuto@rbacCliTest.onmicrosoft.com';
  process.env['AZURE_AD_TEST_PASSWORD'] = 'Pa$$w0rd';
  process.env['AZURE_AD_TEST_GROUP_NAME'] = 'testgroupauto';
  process.env['AZURE_ARM_TEST_LOCATION'] = 'West US';
  process.env['AZURE_AD_TEST_SP_DISPLAY_NAME'] = 'mytestapprandomauto0012345';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09?api-version=2015-07-01', '*')
  .reply(201, "{\"properties\":{\"roleName\":\"TestRole_2c1fe5a3-c5af-42da-a2f9-14f358cc89e3\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:31.8258981Z\",\"updatedOn\":\"2015-11-17T18:04:31.8258981Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"c5dcaf79-12d0-40e3-abf3-adadc2b00d09\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '03f5a95c-ccbf-45b2-a60e-62c9407de9df',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_0',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': '38339243-1dfb-4392-8375-da80c5a57a19',
  'x-ms-routing-request-id': 'WESTUS:20151117T180433Z:38339243-1dfb-4392-8375-da80c5a57a19',
  date: 'Tue, 17 Nov 2015 18:04:32 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09?api-version=2015-07-01', '*')
  .reply(201, "{\"properties\":{\"roleName\":\"TestRole_2c1fe5a3-c5af-42da-a2f9-14f358cc89e3\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:31.8258981Z\",\"updatedOn\":\"2015-11-17T18:04:31.8258981Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"c5dcaf79-12d0-40e3-abf3-adadc2b00d09\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '03f5a95c-ccbf-45b2-a60e-62c9407de9df',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_0',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': '38339243-1dfb-4392-8375-da80c5a57a19',
  'x-ms-routing-request-id': 'WESTUS:20151117T180433Z:38339243-1dfb-4392-8375-da80c5a57a19',
  date: 'Tue, 17 Nov 2015 18:04:32 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09?api-version=2015-07-01')
  .reply(200, "{\"properties\":{\"roleName\":\"TestRole_2c1fe5a3-c5af-42da-a2f9-14f358cc89e3\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:31.8258981Z\",\"updatedOn\":\"2015-11-17T18:04:31.8258981Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"c5dcaf79-12d0-40e3-abf3-adadc2b00d09\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '28b22507-ce94-4aba-9564-017b9ee4d824',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_0',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': '1d013fe8-8a5e-4684-8f6c-0183a57f42a7',
  'x-ms-routing-request-id': 'WESTUS:20151117T180433Z:1d013fe8-8a5e-4684-8f6c-0183a57f42a7',
  date: 'Tue, 17 Nov 2015 18:04:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09?api-version=2015-07-01')
  .reply(200, "{\"properties\":{\"roleName\":\"TestRole_2c1fe5a3-c5af-42da-a2f9-14f358cc89e3\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:31.8258981Z\",\"updatedOn\":\"2015-11-17T18:04:31.8258981Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"c5dcaf79-12d0-40e3-abf3-adadc2b00d09\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '28b22507-ce94-4aba-9564-017b9ee4d824',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_0',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': '1d013fe8-8a5e-4684-8f6c-0183a57f42a7',
  'x-ms-routing-request-id': 'WESTUS:20151117T180433Z:1d013fe8-8a5e-4684-8f6c-0183a57f42a7',
  date: 'Tue, 17 Nov 2015 18:04:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09?api-version=2015-07-01')
  .reply(200, "{\"properties\":{\"roleName\":\"TestRole_2c1fe5a3-c5af-42da-a2f9-14f358cc89e3\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:31.8258981Z\",\"updatedOn\":\"2015-11-17T18:04:31.8258981Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"c5dcaf79-12d0-40e3-abf3-adadc2b00d09\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '036957f7-0fd2-42af-88ee-642130f035cc',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': 'e3dc5c7d-6e2d-4c67-bc9d-de5f55a1a84d',
  'x-ms-routing-request-id': 'WESTUS:20151117T180434Z:e3dc5c7d-6e2d-4c67-bc9d-de5f55a1a84d',
  date: 'Tue, 17 Nov 2015 18:04:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('//subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09?api-version=2015-07-01')
  .reply(200, "{\"properties\":{\"roleName\":\"TestRole_2c1fe5a3-c5af-42da-a2f9-14f358cc89e3\",\"type\":\"CustomRole\",\"description\":\"Custom Role Test Desc\",\"scope\":null,\"assignableScopes\":[\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f\"],\"permissions\":[{\"actions\":[\"Microsoft.Authorization/*/read\",\"Microsoft.Support/*\"],\"notActions\":[]}],\"createdOn\":\"2015-11-17T18:04:31.8258981Z\",\"updatedOn\":\"2015-11-17T18:04:31.8258981Z\",\"createdBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\",\"updatedBy\":\"f8d526a0-54eb-4941-ae69-ebf4a334d0f0\"},\"id\":\"/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/providers/Microsoft.Authorization/roleDefinitions/c5dcaf79-12d0-40e3-abf3-adadc2b00d09\",\"type\":\"Microsoft.Authorization/roleDefinitions\",\"name\":\"c5dcaf79-12d0-40e3-abf3-adadc2b00d09\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '751',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '036957f7-0fd2-42af-88ee-642130f035cc',
  'x-ms-gateway-service-instanceid': 'PASFE_IN_3',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'set-cookie': [ 'x-ms-gateway-slice=productiona; path=/' ],
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': 'e3dc5c7d-6e2d-4c67-bc9d-de5f55a1a84d',
  'x-ms-routing-request-id': 'WESTUS:20151117T180434Z:e3dc5c7d-6e2d-4c67-bc9d-de5f55a1a84d',
  date: 'Tue, 17 Nov 2015 18:04:34 GMT',
  connection: 'close' });
 return result; }]];
 exports.uuidsGenerated = function() { return ['2c1fe5a3-c5af-42da-a2f9-14f358cc89e3','c5dcaf79-12d0-40e3-abf3-adadc2b00d09'];};